name: champion_stage_generator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_colorpicker: any
  dotted_border: any
  image_picker: any
  image_cropper: any
  permission_handler: any
  fluttertoast: any
  save_in_gallery: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true